language: node_js
node_js:
  - '11'
matrix:
  include:
    -   os: linux
        dist: xenial
        sudo: required
    -   os: osx
        osx_image: xcode10.2
    -   os: windows
  allow_failures:
    -   os: osx
    -   os: windows
cache:
  yarn: true
notifications:
  email: false
script:
  - yarn lint
  - yarn test:unit
  - electron-forge package
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - mocha tests/e2e
#deploy:
#  provider: releases
#  api_key: $ENCRYPTED_GITHUB_TOKEN
#  skip_cleanup: true
#  on:
#    tags: true
